In [94]:
import numpy as np
import pandas as pd

#open text file
with open('input14.txt') as f:
    data = f.readlines()

ls = []
for x in data:    
    ls.append(list(x.strip()))
data_arr = np.array(ls) 
data_arr



def get_cols(r):
    all_lists = []
    all_lists_id = []
    sub_list=[]
    sub_ids = []
    for i,x in enumerate(r):
        if x=="#":
            all_lists.append(sub_list)
            all_lists_id.append(sub_ids)
            sub_list =[]
            sub_ids= []
        else:
            sub_list.append(x)
            sub_ids.append(i)
    all_lists.append(sub_list)
    all_lists_id.append(sub_ids)

    return all_lists,all_lists_id

def get_new_order(arr,order):
    ls =[]
    for x in arr:
        ls.append(sorted(x,reverse=order))
    return ls

def north_south(is_north):
    for x in range(0,len(data_arr[0])):
        r = data_arr[:,x]
        vals,orders = get_cols(r)
   
        updated = get_new_order(vals,is_north)
        for i,v in enumerate(updated):
            if updated!=[]:
                data_arr[orders[i],x] = v

def east_west(is_west):
    for x in range(0,len(data_arr)):
        r = data_arr[x,:]
        vals,orders = get_cols(r)
        
        updated = get_new_order(vals,is_west)
        for i,v in enumerate(updated):
            if updated!=[]:
                data_arr[x,orders[i]] = v

output =[]
range_ = 0
for z in range(0,70):
    for x in range(range_,range_+z):
        north_south(True)
        east_west(True)
        north_south(False)
        east_west(False)

    output.append(np.sum(np.sum(data_arr == 'O',axis=1)*((np.arange(0,len(data_arr)))[::-1]+1)))


#np.sum(np.sum(data_arr == 'O',axis=1)*((np.arange(0,len(data_arr)))[::-1]+1))
np.unique(np.array(output))


array([94479, 94601, 94724, 94836, 95024, 95160, 95247, 95525, 95779,
       96067, 96225, 96405, 96590, 96758, 96764, 96785, 96786, 96851,
       96856, 96927, 96928, 96955, 96962, 97044, 97068, 97074, 97185,
       97189, 97241, 97250])

In [54]:
array([94479, 94601, 94724, 94836, 95024, 95160, 95247, 95525, 95779,
       96067, 96225, 96405, 96590, 96758, 96764, 96786, 96851, 96856,
       96927, 96928, 97068, 97074, 97185, 97189, 97241, 97250])



[['O', '.', '.', '.', '.', '#', '.', '.', '.', '.'],
 ['O', '.', 'O', 'O', '#', '.', '.', '.', '.', '#'],
 ['.', '.', '.', '.', '.', '#', '#', '.', '.', '.'],
 ['O', 'O', '.', '#', 'O', '.', '.', '.', '.', 'O'],
 ['.', 'O', '.', '.', '.', '.', '.', 'O', '#', '.'],
 ['O', '.', '#', '.', '.', 'O', '.', '#', '.', '#'],
 ['.', '.', 'O', '.', '.', '#', 'O', '.', '.', 'O'],
 ['.', '.', '.', '.', '.', '.', '.', 'O', '.', '.'],
 ['#', '.', '.', '.', '.', '#', '#', '#', '.', '.'],
 ['#', 'O', 'O', '.', '.', '#', '.', '.', '.', '.'],
 104,
 87,
 69,
 64,
 69,
 63,
 65,
 65,
 63,
 69,
 64,
 69,
 63,
 65,
 65,
 63,
 69,
 64,
 69,
 63]

In [111]:
np.unique(np.array(output)[np.array(output) > 97068]) #97189 too low #97250 not right

array([97074, 97185, 97189, 97241, 97250])

In [91]:
np.array(output)

array([104,  87,  69,  64,  69,  63,  65,  65,  63,  69,  64,  69,  63,
        65,  65,  63,  69,  64,  69,  63,  65,  65,  63,  69,  64,  69,
        63,  65,  65,  63])

In [92]:
1000000000 % 7

6

In [109]:
np.array(output)==97250

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [110]:
1000000000 % 27

1

In [114]:
np.unique(np.array(output))[np.unique(np.array(output)) > 97189]

array([97241, 97250])