In [1]:
import numpy as np
import pandas as pd

#open text file 
with open('input17.txt') as f:
    data = f.readlines()
ls = []
for x in data:
    ls.append(list(x.strip()))
arr  = np.array(ls,dtype=int)
arr

array([[2, 4, 1, 3, 4, 3, 2, 3, 1, 1, 3, 2, 3],
       [3, 2, 1, 5, 4, 5, 3, 5, 3, 5, 6, 2, 3],
       [3, 2, 5, 5, 2, 4, 5, 6, 5, 4, 2, 5, 4],
       [3, 4, 4, 6, 5, 8, 5, 8, 4, 5, 4, 5, 2],
       [4, 5, 4, 6, 6, 5, 7, 8, 6, 7, 5, 3, 6],
       [1, 4, 3, 8, 5, 9, 8, 7, 9, 8, 4, 5, 4],
       [4, 4, 5, 7, 8, 7, 6, 9, 8, 7, 7, 6, 6],
       [3, 6, 3, 7, 8, 7, 7, 9, 7, 9, 6, 5, 3],
       [4, 6, 5, 4, 9, 6, 7, 9, 8, 6, 8, 8, 7],
       [4, 5, 6, 4, 6, 7, 9, 9, 8, 6, 4, 5, 3],
       [1, 2, 2, 4, 6, 8, 6, 8, 6, 5, 5, 6, 3],
       [2, 5, 4, 6, 5, 4, 8, 8, 8, 7, 7, 3, 5],
       [4, 3, 2, 2, 6, 7, 4, 6, 5, 5, 5, 3, 3]])

In [169]:

matr = arr

nodes = [(0,0)]

directions = [(0,1),(1,0),(0,-1),(-1,0)]
visited = np.array([False] * len(np.ravel(matr)) ).reshape(np.shape(matr)[0],np.shape(matr)[1])
min_distance = np.ones((np.shape(matr)[0],np.shape(matr)[1])) * 1000
min_distance[0,0]=matr[0,0]
direction_x = np.zeros((np.shape(matr)[0],np.shape(matr)[1]))
direction_y = np.zeros((np.shape(matr)[0],np.shape(matr)[1]))
straight_line_count =  np.zeros((np.shape(matr)[0],np.shape(matr)[1]))

#get neighbour coords
def get_neighbour_coords(node,direction):
    x,y = np.array(node)+np.array(direction)
    coords = None
    if x >=0 and x < np.shape(matr)[0] and y >=0 and y < np.shape(matr)[1]:
        coords = (x,y)
    return coords

#visited
def get_neighbour_val(neighbour):
    x,y = neighbour
    val = 100000
    if x >=0 and x < np.shape(matr)[0] and y >=0 and y < np.shape(matr)[1]:
        val = matr[x,y]
    return val


while len(nodes) > 0:


    new_nodes= []
    for n in nodes:
       
        visited[n]=True
        #check neighbours
        root_val = min_distance[n]
        root_straight = straight_line_count[n]
       
        for d in directions:
            neighbour = get_neighbour_coords(n,d)
            if neighbour is not None:
                 
                X,Y = d

                  
               
                if root_val + get_neighbour_val(neighbour) < min_distance[neighbour]:
                
                   
                    same_direction =  (X,Y)== (direction_x[n],direction_y[n]) 
                    count = (1+ straight_line_count[n]) if same_direction else 1

                    if count < 20:
                        direction_x[neighbour]=X
                        direction_y[neighbour]=Y
                        straight_line_count[neighbour] =(1+ straight_line_count[n]) if same_direction else 1
                        min_distance[neighbour] = root_val + get_neighbour_val(neighbour)


            
                if not visited[neighbour]:
                    new_nodes.append(neighbour)
                    

    new_nodes = list(set(new_nodes))
    new_nodes = sorted(new_nodes,key=lambda x: min_distance[x])
    
    nodes  = new_nodes
    
min_distance





array([[ 2.,  6.,  7., 10., 14., 17., 19., 22., 23., 24., 27., 29., 32.],
       [ 5.,  7.,  8., 13., 17., 22., 22., 27., 26., 29., 33., 31., 34.],
       [ 8.,  9., 13., 18., 19., 23., 27., 33., 31., 33., 35., 36., 38.],
       [11., 13., 17., 23., 24., 31., 32., 40., 35., 38., 39., 41., 40.],
       [15., 18., 21., 27., 30., 35., 39., 47., 41., 45., 44., 44., 46.],
       [16., 20., 23., 31., 35., 44., 47., 54., 50., 53., 48., 49., 50.],
       [20., 24., 28., 35., 43., 50., 53., 62., 58., 60., 55., 55., 56.],
       [23., 29., 31., 38., 46., 53., 60., 69., 65., 69., 61., 60., 59.],
       [27., 33., 36., 40., 49., 55., 62., 71., 73., 75., 69., 68., 66.],
       [31., 36., 42., 44., 50., 57., 66., 75., 81., 79., 73., 73., 69.],
       [32., 34., 36., 40., 46., 54., 60., 68., 74., 79., 78., 78., 72.],
       [34., 39., 40., 46., 51., 55., 63., 71., 79., 84., 85., 80., 77.],
       [38., 41., 42., 44., 50., 57., 61., 67., 72., 77., 82., 83., 80.]])

In [144]:
straight_line_count
 

array([[0., 1., 2., 3., 4., 5., 6., 7., 1., 1., 1., 1., 1.],
       [1., 1., 2., 3., 4., 5., 1., 1., 1., 2., 3., 4., 5.],
       [2., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 2., 1.],
       [3., 2., 1., 2., 2., 1., 3., 1., 2., 1., 1., 1., 2.],
       [4., 3., 1., 1., 3., 1., 4., 1., 3., 1., 2., 1., 3.],
       [5., 1., 2., 3., 4., 1., 5., 1., 4., 2., 3., 1., 1.],
       [6., 1., 1., 1., 5., 1., 6., 1., 5., 3., 4., 2., 1.],
       [7., 1., 2., 1., 2., 3., 7., 1., 6., 4., 5., 3., 2.],
       [1., 1., 3., 1., 2., 3., 4., 5., 7., 5., 6., 4., 3.],
       [1., 2., 4., 1., 1., 2., 3., 4., 5., 1., 7., 5., 4.],
       [1., 3., 1., 2., 1., 2., 3., 4., 5., 6., 7., 6., 5.],
       [1., 4., 1., 1., 1., 1., 2., 3., 4., 1., 1., 7., 6.],
       [1., 5., 2., 1., 2., 3., 4., 5., 6., 7., 2., 1., 7.]])